reftec-elasticsearch:
  image: elasticsearch
  ports:
    - '9200:9200'
    - '9300:9300'
reftec-skolverket-import:
  build: .
  entrypoint: node index.js
  links:
    - 'reftec-elasticsearch'
  environment:
    - 'COURSES=/app/data/amnen_och_kurser.xml'
    - 'ELASTICSEARCH=reftec-elasticsearch:9200'
