competency-elasticsearch:
  image: elasticsearch
  ports:
    - '9200:9200'
    - '9300:9300'
competency-data-mining:
  build: .
  entrypoint: node index.js
  links:
    - 'competency-elasticsearch'
  environment:
    - 'COURSES=/app/data/amnen_och_kurser.xml'
    - 'ELASTICSEARCH=competency-elasticsearch:9200'
